skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "MKTPmzcYRt3EWo5oPgQsUt1V5AqQbEPQeq7pQBhMqRj"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
