skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_platform = "HxRsEhSd2zBMTDDmQsiR4jA1ZGjdQVybjXrwHAedJUDJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
